permalink: /:year/:month/:day/:title.html
markdown: kramdown
#pygments: true
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: 彭磊
  email: penglei0901@163.com
  link: http://yansu.org
  weibo: http://weibo.com/penglei0901
  github: http://github.com/hackerboy01

# 站点信息
title: 彭磊的博客 
description: 彭磊的博客
url: http://hackerboy01.gitbub.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xitgn.com1.z0.glb.clouddn.com/hacker.jpg
favicon: http://7xitgn.com1.z0.glb.clouddn.com/hacker.jpg   


# disqus 设置
disqus:
  shortname: hackerboy01
